import type { Metadata } from "next";
import "./globals.css";
import ClientProvider from "./ClientProvider";
import { Toaster } from "sonner";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` antialiased`}>
        <ClientProvider>
          <Toaster richColors position="top-center" duration={3000} />

          <ThemeProvider defaultTheme="dark" attribute="class" enableSystem>
            {children}
          </ThemeProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
